"""Added is_bought field

Revision ID: 2eaa9126a559
Revises: 8841f05bbbd0
Create Date: 2021-12-17 18:11:17.839195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaa9126a559'
down_revision = '8841f05bbbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_bought', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'is_bought')
    # ### end Alembic commands ###
