"""migrate test

Revision ID: f1e9b40c282b
Revises: 4276e3ee3d16
Create Date: 2021-12-20 02:29:42.334731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e9b40c282b'
down_revision = '4276e3ee3d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('phone_number', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'phone_number')
    # ### end Alembic commands ###
